# Generated by Django 5.1.5 on 2025-06-04 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("delivery", "0001_initial"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deliveries",
                to="orders.order",
                verbose_name="Order",
            ),
        ),
        migrations.AddField(
            model_name="deliveryaddress",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery_addresses",
                to="delivery.city",
                verbose_name="City",
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="delivery_address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deliveries",
                to="delivery.deliveryaddress",
                verbose_name="Delivery Address",
            ),
        ),
    ]
