# Generated by Django 5.1.5 on 2025-06-04 13:01

import django.db.models.deletion
import django_ckeditor_5.fields
import mptt.fields
import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Carousel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Slider"
                    ),
                ),
                (
                    "description",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name="Slider description"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=store.models.Carousel.carousel_image_upload_path,
                        verbose_name="Carousel image",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True, max_length=255, null=True, verbose_name="Slider URL"
                    ),
                ),
                (
                    "ordering",
                    models.PositiveSmallIntegerField(
                        blank=True, default=0, verbose_name="Slider ordering"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Active"
                    ),
                ),
                ("time_created", models.DateTimeField(auto_now_add=True)),
                ("time_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Slider",
                "verbose_name_plural": "Sliders",
                "ordering": ["ordering", "-time_created"],
            },
        ),
        migrations.CreateModel(
            name="Industry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Industry name"
                    ),
                ),
                (
                    "description",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name="Industry description"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to=store.models.Industry.industry_image_upload_path,
                        verbose_name="Industry image",
                    ),
                ),
                (
                    "ordering",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Industry ordering"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Active"
                    ),
                ),
                ("time_created", models.DateTimeField(auto_now_add=True)),
                ("time_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Industry",
                "verbose_name_plural": "Industries",
                "ordering": ["ordering"],
            },
        ),
        migrations.CreateModel(
            name="ProductType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Product type")),
                (
                    "description",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name="Product type description"
                    ),
                ),
                (
                    "ordering",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Product type ordering"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Active"
                    ),
                ),
                ("time_created", models.DateTimeField(auto_now_add=True)),
                ("time_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Product type",
                "verbose_name_plural": "Product types",
                "ordering": ["ordering", "-time_created"],
            },
        ),
        migrations.CreateModel(
            name="ReviewReply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comment",
                    django_ckeditor_5.fields.CKEditor5Field(verbose_name="Review"),
                ),
                ("time_created", models.DateTimeField(auto_now_add=True)),
                ("time_updated", models.DateTimeField(auto_now=True)),
                ("moderated", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Reply",
                "verbose_name_plural": "Replies",
                "ordering": ["-time_created"],
            },
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Vendor name"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Vendor description"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=store.models.Vendor.vendor_image_upload_path,
                        verbose_name="Vendor Image",
                    ),
                ),
                (
                    "ordering",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Vendor ordering"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Active"
                    ),
                ),
                ("time_created", models.DateTimeField(auto_now_add=True)),
                ("time_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Vendor",
                "verbose_name_plural": "Vendors",
                "ordering": ["ordering"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        unique=True,
                        verbose_name="Category name",
                    ),
                ),
                (
                    "description",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name="Category description"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=store.models.Category.category_image_upload_path,
                        verbose_name="Category image",
                    ),
                ),
                (
                    "ordering",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Ordering in category list",
                        verbose_name="Ordering",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Active"
                    ),
                ),
                ("time_created", models.DateTimeField(auto_now_add=True)),
                ("time_updated", models.DateTimeField(auto_now=True)),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="store.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Product"
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=9)),
                (
                    "description",
                    django_ckeditor_5.fields.CKEditor5Field(
                        verbose_name="Product description"
                    ),
                ),
                (
                    "generated_description",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name="AI generated product description"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=store.models.Product.product_image_upload_path,
                        verbose_name="Product Image",
                    ),
                ),
                (
                    "ordering",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        db_index=True,
                        default=0,
                        help_text="Use for ordering",
                    ),
                ),
                ("time_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("time_updated", models.DateTimeField(auto_now=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=False)),
                (
                    "popular_products",
                    models.BooleanField(default=False, verbose_name="Popularity"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="store.category",
                        verbose_name="Category",
                    ),
                ),
                (
                    "industry",
                    models.ManyToManyField(
                        related_name="Industries", to="store.industry"
                    ),
                ),
                (
                    "product_type",
                    models.ManyToManyField(
                        related_name="product_types", to="store.producttype"
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["ordering"],
            },
        ),
        migrations.CreateModel(
            name="ProductImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        upload_to=store.models.ProductImages.product_extra_image_upload_path,
                        verbose_name="Product image",
                    ),
                ),
                (
                    "alt",
                    models.CharField(blank=True, max_length=125, verbose_name="name"),
                ),
                (
                    "ordering",
                    models.PositiveSmallIntegerField(
                        blank=True, default=0, help_text="Use for ordering"
                    ),
                ),
                ("time_created", models.DateTimeField(auto_now_add=True)),
                ("time_updated", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Extended Product Image",
                "verbose_name_plural": "Extended Product Images",
                "ordering": ["product", "ordering"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.BooleanField(blank=True, null=True)),
                ("advantages", models.CharField(max_length=255)),
                ("disadvantages", models.CharField(max_length=255)),
                (
                    "comment",
                    django_ckeditor_5.fields.CKEditor5Field(verbose_name="Review"),
                ),
                ("moderated", models.BooleanField(default=False)),
                ("time_created", models.DateTimeField(auto_now_add=True)),
                ("time_updated", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="store.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Review",
                "verbose_name_plural": "Reviews",
                "ordering": ["-time_created"],
            },
        ),
    ]
